// functions/confirm_attendance.js
/*
  Firebase Cloud Function: Attendance Confirmation API
  -------------------------------------------------
  - HTTP POST endpoint (`/confirmAttendance`).
  - Expects a JSON payload with `confirmationId` (generated by the
    late‑arrival warning function) and optionally `userId` for extra safety.
  - Looks up the `confirmations/{confirmationId}` document.
  - If the document exists and `expiresAt` is still in the future, the
    function:
      • Marks the confirmation as `confirmed`.
      • Cancels any related enforcement action (by updating the
        corresponding `enforcement` document's `status` to `canceled`).
  - If the confirmation has expired, the request is rejected with a
    400 response.
  - Returns a concise JSON response indicating success or the reason for
    failure.
*/

const functions = require('firebase-functions');
const { admin, db } = require('./lib/firebase');

/**
 * HTTP POST endpoint for confirming attendance.
 *
 * Expected request body (JSON):
 *   {
 *     "confirmationId": "<document-id>",
 *     "userId": "<uid>"   // optional, can be used for extra validation
 *   }
 */
exports.confirmAttendance = functions.https.onRequest(async (req, res) => {
    // Allow only POST
    if (req.method !== 'POST') {
        return res.status(405).send({ error: 'Method Not Allowed' });
    }

    const { confirmationId, userId } = req.body || {};
    if (!confirmationId) {
        return res.status(400).send({ error: 'Missing confirmationId' });
    }

    try {
        const confirmationRef = db.collection('confirmations').doc(confirmationId);
        const confirmationSnap = await confirmationRef.get();

        if (!confirmationSnap.exists) {
            return res.status(404).send({ error: 'Confirmation not found' });
        }

        const confirmation = confirmationSnap.data();
        const now = admin.firestore.Timestamp.now();

        // Optional extra safety: ensure the caller is the same user
        if (userId && confirmation.userId !== userId) {
            return res.status(403).send({ error: 'User mismatch' });
        }

        // Check expiration
        if (confirmation.expiresAt && confirmation.expiresAt.toMillis() < Date.now()) {
            // Mark as expired for audit purposes
            await confirmationRef.update({ status: 'expired' });
            return res.status(400).send({ error: 'Confirmation window has expired' });
        }

        // At this point the confirmation is valid – mark it as confirmed
        await confirmationRef.update({ status: 'confirmed', confirmedAt: now });

        // ---------------------------------------------------------------
        // Cancel any related enforcement action (if one exists)
        // ---------------------------------------------------------------
        if (confirmation.bookingId) {
            const enforcementQuery = await db
                .collection('enforcement')
                .where('bookingId', '==', confirmation.bookingId)
                .where('decision', '==', 'abusive')
                .limit(1)
                .get();

            if (!enforcementQuery.empty) {
                const enforcementRef = enforcementQuery.docs[0].ref;
                await enforcementRef.update({ decision: 'canceled', canceledAt: now });
            }
        }

        return res.status(200).send({
            success: true,
            message: 'Attendance confirmed, enforcement cancelled (if applicable)',
            confirmationId,
        });
    } catch (err) {
        console.error('Error in confirmAttendance:', err);
        return res.status(500).send({ error: 'Internal server error' });
    }
});
